interface Env {
  DATABASE_URL: string;
  BETTER_AUTH_URL?: string;
  BETTER_AUTH_SECRET?: string;
  PAYMENT_LAUNCH_APPROVED?: string;
  CDP_API_KEY_ID?: string;
  CDP_API_KEY_SECRET?: string;
  CDP_WALLET_SECRET?: string;
  CDP_TREASURY_ACCOUNT_NAME?: string;
  COINBASE_ONRAMP_PROJECT_ID?: string;
  COINBASE_ONRAMP_REDIRECT_URL?: string;
  BASE_RPC_URL?: string;
  USDC_BASE_CONTRACT_ADDRESS?: string;
  PAYMENTS_MIN_CONFIRMATIONS?: string;
  PAYMENTS_INITIAL_SCAN_BLOCKS?: string;
  PAYMENTS_SCAN_START_BLOCK?: string;
}
