interface Env {
  DATABASE_URL: string;
  BETTER_AUTH_URL?: string;
  BETTER_AUTH_SECRET?: string;
  PAYMENT_LAUNCH_APPROVED?: string;
  STRIPE_SECRET_KEY?: string;
  STRIPE_WEBHOOK_SECRET?: string;
  STRIPE_SUCCESS_URL?: string;
  STRIPE_CANCEL_URL?: string;
  STRIPE_CONNECT_RETURN_URL?: string;
  STRIPE_CONNECT_REFRESH_URL?: string;
}
