interface Env {
  DATABASE_URL: string;
  RESOLUTION_QUEUE: Queue;
  EXA_API_KEY?: string;
  OPENAI_API_KEY?: string;
  PIPEDREAM_CLIENT_ID?: string;
  PIPEDREAM_CLIENT_SECRET?: string;
  PIPEDREAM_PROJECT_ID?: string;
  PIPEDREAM_PROJECT_ENVIRONMENT?: string;
}
