interface Env {
  DATABASE_URL: string;
  CHALLENGE_OBJECT: DurableObjectNamespace;
  BETTER_AUTH_URL?: string;
  BETTER_AUTH_SECRET?: string;
  GOOGLE_CLIENT_ID?: string;
  GOOGLE_CLIENT_SECRET?: string;
  DEV_USER_HEADER_ENABLED?: string;
  STRIPE_SECRET_KEY?: string;
  STRIPE_WEBHOOK_SECRET?: string;
  STRIPE_SUCCESS_URL?: string;
  STRIPE_CANCEL_URL?: string;
  PIPEDREAM_CLIENT_ID?: string;
  PIPEDREAM_CLIENT_SECRET?: string;
  PIPEDREAM_PROJECT_ID?: string;
  PIPEDREAM_PROJECT_ENVIRONMENT?: string;
  PIPEDREAM_ALLOWED_ORIGINS?: string;
  TESTING_MODE_EMAILS?: string;
  API_INTERNAL_URL?: string;
  RESOLVER_URL?: string;
  RESOLVER_TEST_TOKEN?: string;
}
